### ISSUE TITLE
Theme font not work for me..

### ISSUE THREAD

**Issue by Se7Touch** [Teraskull/bigsur-grub2-theme#1]
Hello, first of all, I would like to express that I really like your work. I have done the theme installation but the font has not changed.

Any idea why it might happen?

I am using Grub2.05.

**Comment by Teraskull** [comment]
Hi, unfortunately, the font cannot be smooth, or anti-aliased, due to limitations of GRUB. The theme illustration on the screenshots was made digitally, since it is not possible to take a screenshot while in GRUB.

I tried to make the fonts as similar as possible. There is no problem on your side. It's just that GRUB does not render fonts, but rather uses bitmap images, which is why they look so sharp.

 I will see if there is any workaround for this.

Thanks for using this theme!

**Comment by Se7Touch** [comment]
It looks this bad because my screen resolution is 1024x768. thanks a lot my friend.

**Comment by Teraskull** [comment]
Closed for now.
