### ISSUE TITLE
OS Icons for RHEL based distros, like RockyLinux and AlmaLinux?

### ISSUE THREAD

**Issue by SoapDev2018** [Teraskull/bigsur-grub2-theme#12]
Hi!
Could you please add OS icons for RHEL based distros like RockyLinux and AlmaLinux?
Or, could you provide some site from where I could potentially download those from, and perhaps contribute to the repository as well?

**Comment by Teraskull** [comment]
Hi!

Unfortunately, I lost the original icon source and cannot add new ones because the style would not match the existing ones.

I couldn't find any good monochromatic icon packs either.

This [reddit post](https://www.reddit.com/r/linux/comments/nt1tm9/) has a nice set of colored icons, and I assume it would be simple to just convert them to white, but they will probably look bad when scaled down to 32x32.

I'd love to add more icons as long as they are consistent, but there aren't any good options that I found.

**Comment by Teraskull** [comment]
Found this amazing icon pack: https://simpleicons.org/

In case you want to manually export the SVG as a 32x32px icon.

**Comment by SoapDev2018** [comment]
Great find, @Teraskull !
Do you mind if I contribute some icons from that site (after testing), with proper acknowledgement of the source of the icons, as a PR?

**Comment by Teraskull** [comment]
Absolutely, I appreciate it, thanks!

**Comment by SoapDev2018** [comment]
Hi, converting the SVG color to white directly and exporting as 32x32 PNG is creating a bigger image.
Are there any settings I need to mess with?
![rockylinux](https://github.com/user-attachments/assets/4e1cdde7-5bc0-44ec-93bf-b53629fc6f56)
