### ISSUE TITLE
Icons not showing on Ventoy

### ISSUE THREAD

**Issue by rasgajag** [Teraskull/bigsur-grub2-theme#7]
How do I get the icons to show for the diffrent iso files on ventoy?

**Comment by Teraskull** [comment]
Hi,

Your ISO files should have any of these names in the filename to be shown in the Ventoy interface:
https://github.com/Teraskull/bigsur-grub2-theme/blob/2e8139afd2b6e4cb2dcaf85d8248cbc10d556c6b/ventoy/ventoy.json#L18-L219

So for example, a Fedora ISO with the name `Fedora-Workstation-Live-x86_64-37-1.7` will show the Fedora icon, because it has the `Fedora` in the filename.

Hope this helps!
